### ISSUE TITLE
fire.Fire(main) failed, a bug?

### ISSUE THREAD

**Issue by huxian0402** [Zeqiang-Lai/Mini-DALLE3#6]
@whai362 When I use the command "python -m minidalle3.web" to launch the demo, I encounter the following error. It seems that there is a failure in starting "fire.Fire(main)". Could you please help me understand the reason behind this?

Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:34<00:00,  4.97s/it]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 7/7 [02:27<00:00, 21.08s/it]
/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/gradio/blocks.py:928: UserWarning: api_name add_text already exists, using add_text_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/gradio/blocks.py:928: UserWarning: api_name bot already exists, using bot_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/gradio/blocks.py:928: UserWarning: api_name lambda already exists, using lambda_1
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/gradio/blocks.py:928: UserWarning: api_name lambda already exists, using lambda_2
  warnings.warn(f"api_name {api_name} already exists, using {api_name_}")
Traceback (most recent call last):
  File "/home/mi/anaconda3/envs/dfuxl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mi/anaconda3/envs/dfuxl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mi/Desktop/project/Mini-DALLE3/minidalle3/web.py", line 137, in <module>
    fire.Fire(main)
  File "/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/mi/Desktop/project/Mini-DALLE3/minidalle3/web.py", line 133, in main
    demo.queue(concurrency_count=max_users).launch(server_port=port, server_name="0.0.0.0", share=share)
  File "/home/mi/anaconda3/envs/dfuxl/lib/python3.8/site-packages/gradio/blocks.py", line 1676, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

**Comment by Zeqiang-Lai** [comment]
Hi there, this is caused by the new version of Gradio. Please pull the latest code and install the packages that follows the versions in requirements.txt.
